package wearetests.web;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class TestapprovefriendRequestTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
//    @After
//    public void tearDown() {
//        driver.quit();
//    }
    @Test
    public void testapprovefriendRequest() {
        // Test name: test-approve-friendRequest
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("http://localhost:8081/");
        // 2 | setWindowSize | 1552x840 |
        driver.manage().window().setSize(new Dimension(1552, 840));
        // 3 | click | css=.nav-item:nth-child(2) > .nav-link |
        driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
        // 4 | click | id=username |
        driver.findElement(By.id("username")).click();
        // 5 | type | id=username | olgaAtanas
        driver.findElement(By.id("username")).sendKeys("Olga");
        // 6 | click | id=password |
        driver.findElement(By.id("password")).click();
        // 7 | type | id=password | dskjflsdkjIOIHDj@kfj21a
        driver.findElement(By.id("password")).sendKeys("123456");
        // 8 | click | css=input:nth-child(10) |
        driver.findElement(By.cssSelector("input:nth-child(10)")).click();
        // 9 | click | css=.nav-item:nth-child(5) > .nav-link |
        driver.findElement(By.cssSelector(".nav-item:nth-child(5) > .nav-link")).click();
        // 10 | click | css=.btn |
        driver.findElement(By.cssSelector(".btn")).click();
        // 11 | click | css=.col-md-12:nth-child(1) .btn |
        driver.findElement(By.cssSelector(".col-md-12:nth-child(1) .btn")).click();
    }
}
